
// ================================================================
//  motor_fault_config.h  -  Auto-generated by pipeline
//  Model: 1D-CNN INT8 | 3 Classes | Accuracy: 100.00%
// ================================================================
#pragma once

// ── Preprocessing ──────────────────────────────────────────────
static const float NORM_MEAN[3] = {0.048073f, -0.182877f, 0.907200f};
static const float NORM_STD[3]  = {0.209444f,  0.146853f,  0.084246f};

// ── Quantization ───────────────────────────────────────────────
static const float  INPUT_SCALE       = 0.08001178f;
static const int8_t INPUT_ZERO_POINT  = 11;
static const float  OUTPUT_SCALE      = 0.00390625f;
static const int8_t OUTPUT_ZERO_POINT = -128;

// ── Window config ──────────────────────────────────────────────
#define WINDOW_SIZE   200    // samples (2.0s @ 100Hz)
#define STRIDE_SIZE   50    // samples (0.5s)
#define N_CHANNELS    3     // x, y, z
#define N_CLASSES     3

// ── Class labels ───────────────────────────────────────────────
static const char* CLASS_NAMES[N_CLASSES] = {
    "Tat",          // 0 - Tat
    "Binh_thuong",  // 1 - Binh thuong
    "Lech_tam",     // 2 - Lech tam
};

/*
 * INFERENCE FLOW (ESP32-S3):
 *
 * float raw[WINDOW_SIZE][N_CHANNELS];
 * int8_t input_buf[WINDOW_SIZE * N_CHANNELS];
 *
 * // 1. Normalize + Quantize
 * for (int i = 0; i < WINDOW_SIZE; i++) {
 *     for (int c = 0; c < N_CHANNELS; c++) {
 *         float norm = (raw[i][c] - NORM_MEAN[c]) / NORM_STD[c];
 *         int q = (int)roundf(norm / INPUT_SCALE) + INPUT_ZERO_POINT;
 *         q = (q < -128) ? -128 : (q > 127) ? 127 : q;
 *         input_buf[i * N_CHANNELS + c] = (int8_t)q;
 *     }
 * }
 *
 * // 2. Run inference
 * input->data.int8 = input_buf;
 * interpreter->Invoke();
 *
 * // 3. Dequantize output
 * int8_t* out = output->data.int8;
 * float probs[N_CLASSES];
 * for (int i = 0; i < N_CLASSES; i++) {
 *     probs[i] = (out[i] - OUTPUT_ZERO_POINT) * OUTPUT_SCALE;
 * }
 * int predicted = argmax(probs);  // CLASS_NAMES[predicted]
 */
